language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - BOARD=esp32dev PLATFORMIO_CI_SRC=examples/Hasher/Hasher.ino
    - BOARD=esp32dev PLATFORMIO_CI_SRC=examples/HmacHasher/HmacHasher.ino
install:
    - pip install -U platformio
script:
    - platformio ci -v --lib="." --board=$BOARD $PIO_EXTRAS
