#ifndef CRYPTO_CRYPTOTYPES_H
#define CRYPTO_CRYPTOTYPES_H

enum hash_algo_t {
  HASH_MD2 = 1,
  HASH_MD4,
  HASH_MD5,
  HASH_SHA1,
  HASH_SHA224,
  HASH_SHA256,
  HASH_SHA384,
  HASH_SHA512,
  HASH_RIPEMD160,
};

#endif //CRYPTO_CRYPTOTYPES_H
